### ISSUE TITLE
Picard snap not getting latest stable tag

### ISSUE THREAD

**Issue by pachulo** [Lin-Buo-Ren/selective-checkout-stage-snap#1]
Hi! I'm using [this snap in my picard snap and it's been working fine](https://github.com/pachulo/musicbrainz-picard-snap/blob/picard-2.x/snap/snapcraft.yaml#L67) so far. Right now I have a problem thought: it's not taking the latest stable tag from their repo:

- https://github.com/metabrainz/picard/releases

The only thing that changed from previous releases is that the tag is not on the master branch, but on a branch:

- https://github.com/metabrainz/picard/tree/2.2.3

Is this a bug or something expected? Thanks!

**Comment by Lin-Buo-Ren** [comment]
It's likely a bug, thanks for the heads-up.

Marc <notifications@github.com> 於 2019年12月6日 週五 上午7:03 寫道：

**Comment by pachulo** [comment]
Any news on this?

Thanks for your work!

**Comment by pachulo** [comment]
I've been testing this more and I'm not really sure if I'm missing something...This is what I'm doing:

```
$ git clone https://github.com/metabrainz/picard
$ git clone https://github.com/Lin-Buo-Ren/selective-checkout-stage-snap
$ cd picard
$ env SNAPCRAFT_PROJECT_NAME=picard ../selective-checkout-stage-snap/snap/local/scriptlets/selective-checkout \
--stable-tag-pattern=release-[[:digit:]].[[:digit:]].[[:digit:]]$ \
--release-tag-prefix=^release- \
--beta-tag-pattern=^release-[[:digit:]].[[:digit:]].[[:digit:]]a[[:digit:]]$ \
--force-stable \
--dry-run
```
Then I get this output:
```
selective-checkout: The last tagged stable release(release-2.2.3) hasn't been promoted to the stable channel(2.2.2) on the Snap Store yet, checking out release-2.2.3.
HEAD ara és a f2c1d58f Release 2.2.3
selective-checkout: Snap version determined to be "release-2.2.3".
```

But, if I understood correctly, snap version should be `2.2.3`, because the value of `--release-tag-prefix` should be "be stripped from the resulting snap’s version string.":

* https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617

Am I doing something wrong?

**Comment by pachulo** [comment]
OK, I got it working with the `--dry-run`:

```
$ env SNAPCRAFT_PROJECT_NAME=picard ../selective-checkout-stage-snap/snap/local/scriptlets/selective-checkout \
--stable-tag-pattern=^[[:digit:]].[[:digit:]].[[:digit:]]$ \
--release-tag-prefix='release-' \
--force-stable \
--dry-run
selective-checkout: The last tagged stable release(2.2.3) hasn't been promoted to the stable channel(2.2.2) on the Snap Store yet, checking out 2.2.3.
HEAD now is at f2c1d58f Release 2.2.3
selective-checkout: Snap version determined to be "2.2.3".
```

But then, using the same command on my snapcraft.yml, it doesn't take the latest release:
(From https://launchpadlibrarian.net/461729927/buildlog_snap_ubuntu_bionic_amd64_picard-2.0-snap_BUILDING.txt.gz)
```
selective-checkout: The last tagged stable release(2.2.2) hasn't been promoted to the stable channel(2.2.2) on the Snap Store yet, checking out 2.2.2.
Note: checking out 'release-2.2.2'.
```
Do you know what is going on @Lin-Buo-Ren ?

**Comment by pachulo** [comment]
OK, I found the issue: I needed to get the full repository and not just the latest 1000 commits:

- https://github.com/pachulo/musicbrainz-picard-snap/commit/6bfd957f87df8d7de0b24b9d257ac4dfec342184
